# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.



development:
  secret_key_base: 54a839fe664134dd1fe28bd2b898ea8c1609b2f637e2063d13dbeb1c83249aa8df7b57d148887e7e2cff6f14c4b1fa5e6755245fb15bd45c9635430d716b9a7b
  facebook_app_key: '726741267455198'

test:
  secret_key_base: a45d8ff911fbb7be20ec0c0e45124dd858af892d92dfa12115da47a3c661fd13c062d9269a688db73a2e863cef99cd01947b04c96556f5db880d5138e0cbe1ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 08b454979b28e7babab8e95ce8f8ae1187bb6d40cfb122aaba56f8cc3c722dc23c66cc270d983978a424b81b2ae8172e5424b7a0c11eab953f0633d5f7c96ba4
  facebook_app_key: '972497566099345'